### ISSUE TITLE
Error console when I show detail is over display.

### ISSUE THREAD

**Issue by bamossza** [fluttercommunity/flutter_sticky_headers#18]
package >> https://pub.dev/packages/sticky_headers

I have to use the fix header listview, 
but my detail is over display 
but even so I have to make use of freezing.

[/] display not problem when I show detail fit display.
![image](https://user-images.githubusercontent.com/12523400/60069882-cd524c00-973e-11e9-867c-6a40e78fc314.png)

[X] when I show detail is over display (horizontal)
![image](https://user-images.githubusercontent.com/12523400/60069907-e3f8a300-973e-11e9-8554-5b9fc0c26d7c.png)

Finally I resolve by add code in ListView widget below,
```
Add here >>>> scrollDirection: renderer.Axis.horizontal

child: ListView(
                scrollDirection: renderer.Axis.horizontal,
                children: <Widget>[
                  StickyHeader(
                    header: Container(
               .........
               .........
```

![image](https://user-images.githubusercontent.com/12523400/60069894-d93e0e00-973e-11e9-8e0f-ee95240b1666.png)

Display show detail no problem.

-------------

But have Error console Flutter, How to resolve ?

```
I/flutter (26365): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (26365): The following assertion was thrown during performLayout():
I/flutter (26365): RenderStickyHeader does not meet its constraints.
I/flutter (26365): Constraints: BoxConstraints(0.0<=w<=Infinity, h=407.0)
I/flutter (26365): Size: Size(1200.0, 447.0)
I/flutter (26365): If you are not writing your own RenderBox subclass, then this is not your fault. Contact support:
I/flutter (26365): https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (26365): 
I/flutter (26365): When the exception was thrown, this was the stack:
I/flutter (26365): #0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1764:9)
I/flutter (26365): #1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:1823:6)
I/flutter (26365): #2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1543:17)
I/flutter (26365): #3      RenderBox.size= (package:flutter/src/rendering/box.dart:1543:65)
I/flutter (26365): #4      RenderStickyHeader.performLayout (package:sticky_headers/sticky_headers/render.dart:110:5)
I/flutter (26365): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #10     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:165:27)
I/flutter (26365): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #12     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter (26365): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #14     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:407:13)
I/flutter (26365): #15     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1322:12)
I/flutter (26365): #16     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1240:20)
I/flutter (26365): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #36     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:799:17)
I/flutter (26365): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #38     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:799:17)
I/flutter (26365): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #40     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (26365): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #42     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
I/flutter (26365): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #44     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter (26365): #45     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:431:7)
I/flutter (26365): #46     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter (26365): #47     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter (26365): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #49     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #51     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #52     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1206:11)
I/flutter (26365): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #60     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #62     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #64     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #66     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #68     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #69     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3015:13)
I/flutter (26365): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #71     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter (26365): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #73     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #75     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #77     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #79     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #81     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #83     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (26365): #84     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter (26365): #85     RenderView.performLayout (package:flutter/src/rendering/view.dart:151:13)
I/flutter (26365): #86     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1519:7)
I/flutter (26365): #87     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
I/flutter (26365): #88     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:347:19)
I/flutter (26365): #89     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter (26365): #90     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter (26365): #91     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter (26365): #92     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter (26365): #93     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:773:7)
I/flutter (26365): #95     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
I/flutter (26365): #96     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
I/flutter (26365): #97     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
I/flutter (26365): (elided one frame from package dart:async-patch)
I/flutter (26365): 
I/flutter (26365): The following RenderObject was being processed when the exception was fired:
I/flutter (26365):   RenderStickyHeader#b1a40 relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (26365):   creator: StickyHeader ← RepaintBoundary-[<0>] ← IndexedSemantics ←
I/flutter (26365):   NotificationListener<KeepAliveNotification> ← KeepAlive ← AutomaticKeepAlive ← SliverList ←
I/flutter (26365):   MediaQuery ← SliverPadding ← Viewport ← IgnorePointer-[GlobalKey#9c11d] ← Semantics ← ⋯
I/flutter (26365):   parentData: <none> (can use size)
I/flutter (26365):   constraints: BoxConstraints(0.0<=w<=Infinity, h=407.0)
I/flutter (26365):   layer: OffsetLayer#517c4
I/flutter (26365):   size: Size(1200.0, 447.0)
I/flutter (26365): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (26365):   RenderRepaintBoundary#cca85 relayoutBoundary=up6 NEEDS-PAINT
I/flutter (26365):     RenderCustomPaint#61625 relayoutBoundary=up7 NEEDS-PAINT
I/flutter (26365):       RenderRepaintBoundary#00c12 relayoutBoundary=up8 NEEDS-PAINT
I/flutter (26365):         _RenderScrollSemantics#069c0 relayoutBoundary=up9 NEEDS-PAINT
I/flutter (26365):           RenderPointerListener#31d18 relayoutBoundary=up10 NEEDS-PAINT
I/flutter (26365):   RenderConstrainedBox#30f49 relayoutBoundary=up6 NEEDS-PAINT
I/flutter (26365):     RenderDecoratedBox#01306 relayoutBoundary=up7 NEEDS-PAINT
I/flutter (26365):       RenderPadding#53801 relayoutBoundary=up8 NEEDS-PAINT
I/flutter (26365):         RenderPositionedBox#7f27c relayoutBoundary=up9 NEEDS-PAINT
I/flutter (26365):           RenderFlex#67324 relayoutBoundary=up10 NEEDS-PAINT
I/flutter (26365): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

My code

```
import 'package:flutter/rendering.dart' as renderer;
import 'package:sticky_headers/sticky_headers.dart';

Flexible(
  flex: 55,
  child: ListView(
	scrollDirection: renderer.Axis.horizontal,
	children: <Widget>[
	  StickyHeader(
		header: Container(
		  height: 40.0,
		  color: renderer.Color(0xFFD6D8DB),
		  padding: EdgeInsets.symmetric(horizontal: 10.0),
		  alignment: Alignment.centerLeft,
		  child: Row(
			children: <Widget>[
			  Container(
				  child: Text(
					'PLANT',
					style: TextStyle(color: renderer.Color(0xFF212529), fontSize: 14),
				  ),
				  width: 200),
			  Container(
				  child: Text(
					'TYPE',
					style: TextStyle(color: renderer.Color(0xFF212529), fontSize: 14),
				  ),
				  width: 200),
			  Container(
				  child: Text(
					'FULLNAME',
					style: TextStyle(color: renderer.Color(0xFF212529), fontSize: 14),
				  ),
				  width: 200),
			  Container(
				  child: Text(
					'FULLNAME 3',
					style: TextStyle(color: renderer.Color(0xFF212529), fontSize: 14),
				  ),
				  width: 200),
			  Container(
				  child: Text(
					'FULLNAME 2',
					style: TextStyle(color: renderer.Color(0xFF212529), fontSize: 14),
				  ),
				  width: 200),
			  Container(
				  child: Text(
					'FULLNAME 3',
					style: TextStyle(color: renderer.Color(0xFF212529), fontSize: 14),
				  ),
				  width: 200)
			],
		  ),
		),
		content: SingleChildScrollView(
		  child: Column(
			children: _plantOperatorEmployeeData
				.map(
				  (itemRow) => Row(
						children: [

						  Container(
							  padding: EdgeInsets.all(10.0),
							  child: Text(
								'AAAAAA BBBBBB',
								style: TextStyle(color: Colors.green, fontSize: 14),
							  ),
							  width: 200),
						  Container(
							  padding: EdgeInsets.all(10.0),
							  child: Text(
								'AAAAAA BBBBBB',
								style: TextStyle(color: Colors.green, fontSize: 14),
							  ),
							  width: 200),
						  Container(
							  padding: EdgeInsets.all(10.0),
							  child: Text(
								'AAAAAA BBBBBB',
								style: TextStyle(color: Colors.green, fontSize: 14),
							  ),
							  width: 200),
						  Container(
							  padding: EdgeInsets.all(10.0),
							  child: Text(
								'AAAAAA BBBBBB',
								style: TextStyle(color: Colors.green, fontSize: 14),
							  ),
							  width: 200),
						  Container(
							  padding: EdgeInsets.all(10.0),
							  child: Text(
								'AAAAAA BBBBBB',
								style: TextStyle(color: Colors.green, fontSize: 14),
							  ),
							  width: 200),
						  Container(
							  padding: EdgeInsets.all(10.0),
							  child: Text(
								'AAAAAA BBBBBB',
								style: TextStyle(color: Colors.green, fontSize: 14),
							  ),
							  width: 200),
						],
					  ),
				)
				.toList(),
		  ),
		),
	  )
	],
  ),
),
```

Thank you so much.

**Comment by slightfoot** [comment]
Please re-open if you have this problem on Flutter 3.0.0 and sticky_headers: 0.3.0.
